name: ci

on:
  pull_request_target:
    branches:
      - "main"

  release:
    types: [published]

jobs:
  docker-build-publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ github.sha }}
      -
        name: Test docker image
        run: ./tests/test-docker-image.sh ${{ github.repository }}:${{ github.sha }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        if: ${{ success() && github.event_name == 'release' }}
        with:
          push: true
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ github.sha }}
            ${{ github.repository }}:${{ github.ref_name }}
      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        if: ${{ success() && github.event_name == 'release' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ github.repository }}
          short-description: ${{ github.event.repository.description }}
