name: ci

on:
  # release:
  #   types: [published]
  push:
    branches:
      - 'docker-build'

jobs:
  docker-build-publish:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ github.sha }}
      -
        name: Test docker image
        working-directory: tests
        run: ./test-docker-image.sh
      -
        name: Build and push
        uses: docker/build-push-action@v6
        if: ${{ success() }}
        with:
          push: true
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ github.sha }} 
  repo-update:
    runs-on: ubuntu-latest
    needs: [docker-build-publish]
    if: needs.*.result == 'success'
    steps:
      - uses: actions/checkout@v4
      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ github.repository }}
          short-description: ${{ github.event.repository.description }}
